twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    #Con esto los formularios tendran los estilos de bootstrap 4    
    #form_themes: ['bootstrap_4_layout.html.twig']
